In [1]:
# numpy = array processing package

# benefits
#----------
# multidimensional array support/fast
# supports mathematical operations/computation
# mainly supports fourier transform,random number generation,random process,algebric oprations
# provides tools for c c++ fortran code
# ndarray - is a single datatype(homogenous)
import numpy as np

In [2]:
a = [200,300,400,500]
b = [10,20,30,40]
a+b # perfomrs only concatenation not addition of each element in list

[200, 300, 400, 500, 10, 20, 30, 40]

In [3]:
a/b

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [4]:
#CREATING NUMPY ARRAY

In [5]:
np_a = np.array(a)
np_b = np.array(b)
print((np_a))
print((np_b))
#print(type(np_a))
#print(type(np_b))


[200 300 400 500]
[10 20 30 40]


In [6]:
np_a + np_b # performs addition operation on each elent in numpy array

array([210, 320, 430, 540])

In [7]:
np_a / np_b

array([20.        , 15.        , 13.33333333, 12.5       ])

In [8]:
np_a * np_b

array([ 2000,  6000, 12000, 20000])

In [9]:
#types of array
# 1d
# 2d
# 3d

# one dimensional array

one = np.array([3,5,7,9,])
one

array([3, 5, 7, 9])

In [10]:
# 2d
two = np.array([[1,2,3,4,5],[11,22,33,44,55]])
print(two)
#print("number of rows and columns :",two.shape)
#print("dimension of array:",two.ndim)
#print(two.size)
#print(two.dtype)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]


In [11]:
# 3d
three = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                  [[10,11,12],[13,14,15],[16,17,18]],
                 [[19,20,21],[22,23,24],[25,26,27]]])
three

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [12]:
# numpy attributes
#-----------------
# ndim - returns dimension/rank of array
# shape - size of each dimensions(rows,columns) of array
# size - total no of elements in array
# dtype - returns exact datatype

In [13]:
car = np.array([['skoda','Honda','Ford','Suzuki','kia'],
                ['fabia','Accord','ecosport','Baleno','carnival']])
car


array([['skoda', 'Honda', 'Ford', 'Suzuki', 'kia'],
       ['fabia', 'Accord', 'ecosport', 'Baleno', 'carnival']], dtype='<U8')

In [14]:
car.ndim   #No of dimensions

2

In [15]:
car.shape   #row and columns

(2, 5)

In [16]:
car.size  #total elements

10

In [17]:
car.dtype  #data type

dtype('<U8')

In [18]:
#basic operations

In [19]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [20]:
day1 = np.array([4,7,5,2,8,1,3])
day2 = np.array([7,5,3,9,2,4,6])

total = day1 + day2
total

array([11, 12,  8, 11, 10,  5,  9])

In [21]:
print(day1-day2)

[-3  2  2 -7  6 -3 -3]


In [22]:
print(day1*day2)
print(day1/day2)
print(day1>day2)
print(day1<day2)
print(day1>=day2)
print(day1==day2)

[28 35 15 18 16  4 18]
[0.57142857 1.4        1.66666667 0.22222222 4.         0.25
 0.5       ]
[False  True  True False  True False False]
[ True False False  True False  True  True]
[False  True  True False  True False False]
[False False False False False False False]


In [23]:
distance = np.array([[4,6,3,8],[5,6,8,10]])
distance

array([[ 4,  6,  3,  8],
       [ 5,  6,  8, 10]])

In [24]:
first_day = distance[0]
first_day

array([4, 6, 3, 8])

In [25]:
second_day = distance[1]
second_day

array([ 5,  6,  8, 10])

In [26]:
secondperson_day2 = distance[1][1]
secondperson_day2

6

In [27]:
secondperson_day_total = distance[:,1] # here : represents all rows of specified number 1
secondperson_day_total

array([6, 6])

In [28]:
distance[0,:]# represents all column for specified number 0

array([4, 6, 3, 8])

In [29]:
p2p3_total = distance[:,1:3]
p2p3_total

array([[6, 3],
       [6, 8]])

In [30]:
for i in distance:
    print(i)

[4 6 3 8]
[ 5  6  8 10]


In [31]:
good_walk = distance>=8 # condition
good_walk

array([[False, False, False,  True],
       [False, False,  True,  True]])

In [ ]:
print(distance)

In [ ]:
print(distance[good_walk]) # constraint (implied conditions with restrcitions)

In [ ]:
car = np.array(['suzuki','toyotakirloskar','tata','benz','ford'])
car_dup = car

# shallow copy - change made in duplicate will affect the original structure

print(car_dup)

print(car)

car_dup[3] = 'kia'
print('after change made in duplicate')
print('shallow:',car_dup)
print('original:',car)

In [ ]:
car_dup[3]='hindustan motors india'
car_dup

In [ ]:
car

In [ ]:
cview = car.view() # view is similar with shallow copy

In [ ]:
cview

In [ ]:
car

In [ ]:
cview[2] = 'mercedes'

In [ ]:
#shallow copy 
cview

In [ ]:
car

In [ ]:
#deep copy - change made in duplicate wont affect original
deep = car.copy()
deep

In [ ]:
deep[3]='vk'
deep

In [ ]:
car

In [ ]:
#universal functions
sqrt = np.sqrt([144,169,225,289])
sqrt


In [ ]:
np.cos(0)

In [ ]:
np.ceil([4.2,89.6,7.8,-3.4,-9.4])

In [ ]:
np.floor([4.5,89.6,7.8,-3.4,-9.4])

In [ ]:
np.exp([1,2,3,4])

In [ ]:
distance

In [ ]:
# shape manipulation

print(distance.ravel())  # converts and combine any array dimensions into one dimension
print(distance)

#dist = distance.ravel() # naming convention
#print(dist)

In [ ]:
print(distance.reshape(1,8))
print(distance)

In [ ]:
distance.reshape(4,2)

In [ ]:
distance.reshape(8,1)

In [ ]:
distance

In [ ]:
distance = distance.reshape(2,4)
print(distance)

In [ ]:
#print(distance.reshape(4,2))
#deep - never change and dont affect the original structure
print(distance)

In [ ]:
distance.resize(4,2) #shallow - affects original structure # resize will change structure
distance

In [ ]:
distance

In [ ]:
# horizontal splitting

np.hsplit(distance,2)

In [ ]:
# resize - permanently changes the shape of an array

distance.resize(2,4)
distance
#car

In [ ]:
distance.resize(4,2)
distance

In [ ]:
np.hsplit(distance,2)

In [ ]:
day1

In [ ]:
day2

In [ ]:
np.hstack([day1,day2])

In [ ]:
day1

In [ ]:
day1*day2 #number of elements should be equal

In [ ]:
day1

In [ ]:
distance


In [ ]:
# algebric equations

distance.transpose()

In [ ]:
np.linalg.inv(np.array([[2,4],[1,3]]))

In [ ]:
np.trace(np.array([[20,4],[1,53]]))

In [ ]:
# addtional functions for creating arrays
#-----------------------------------------
# array creation using evenly spaced

a = np.arange(10)

print(a)
print(type(a))
#print('numpy arange value:',a)
#print(type(a))
#for i in range(10):
#    print(i,)


In [ ]:
b = np.arange(10,51,5)
b

In [ ]:
# array creation using number points
c = np.linspace(0,1,6) # linspace means linear spacing in between given values
c

In [ ]:
d = np.linspace(0,1,6,endpoint=False)
d


In [4]:
# common array functions
#------------------------
# zeros
# ones
# eye
# diag

e = np.ones((4,4))
e

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
f = np.zeros((4,4))
f

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
g = np.eye(4)
g

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
h = np.diag(np.arange(10,101,10))
print(h)



[[ 10   0   0   0   0   0   0   0   0   0]
 [  0  20   0   0   0   0   0   0   0   0]
 [  0   0  30   0   0   0   0   0   0   0]
 [  0   0   0  40   0   0   0   0   0   0]
 [  0   0   0   0  50   0   0   0   0   0]
 [  0   0   0   0   0  60   0   0   0   0]
 [  0   0   0   0   0   0  70   0   0   0]
 [  0   0   0   0   0   0   0  80   0   0]
 [  0   0   0   0   0   0   0   0  90   0]
 [  0   0   0   0   0   0   0   0   0 100]]


In [10]:
# mersenne twister prng - random number generation using np.random
uniform = np.random.rand(10) # uniform distribution [ 0 - 1]
uniform

array([0.99281927, 0.64903515, 0.86626281, 0.53440682, 0.43435373,
       0.30250826, 0.2946739 , 0.04609151, 0.70344953, 0.17743689])

In [11]:
gaussian = np.random.randn(10) # normal - gaussian [-1,1] [-inf to +inf]
gaussian

array([ 0.43750394,  1.05041028, -0.37347886, -1.81174384,  0.86566562,
        0.41230944,  0.58575374, -0.29283165, -0.07014858, -0.00383135])

In [12]:
s = np.random.seed(4)
s

In [13]:
i = np.arange(200000)
i


array([     0,      1,      2, ..., 199997, 199998, 199999])

In [14]:
%timeit i+1

1.85 ms ± 413 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [15]:
j = np.ones((5,5))
j

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
j * j # string handling - string methods - string repetition

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
j.dot(j)

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [20]:
# broadcasting functions
# tile
k = np.tile(np.arange(0,40,10),(3,1)).T
k

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [22]:
l = np.array([1,2,3])
k + l

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [24]:
m = np.arange(0,51,5)


In [25]:
print(m)

[ 0  5 10 15 20 25 30 35 40 45 50]


In [26]:
m.shape

(11,)

In [27]:
m = m[:,np.newaxis]
m

array([[ 0],
       [ 5],
       [10],
       [15],
       [20],
       [25],
       [30],
       [35],
       [40],
       [45],
       [50]])

In [28]:
m.shape

(11, 1)